// File generated by `flutterfire configure` equivalent
// Generated for iOS and Android

import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLMbhQxz40ZgsgrtbgXtvQRBDXdsKmIBY',
    appId: '1:634227882013:android:66569c1a4f3745fff5eef4',
    messagingSenderId: '634227882013',
    projectId: 'kadirliapplication',
    storageBucket: 'kadirliapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfkTuQxu5mhuB5wRjLB7FnE9DfUP8Ed8o',
    appId: '1:634227882013:ios:866074df51a27e6df5eef4',
    messagingSenderId: '634227882013',
    projectId: 'kadirliapplication',
    storageBucket: 'kadirliapplication.firebasestorage.app',
    iosBundleId: 'com.kadirli.kadirliapp',
  );
}
